describe('Navigate through Pages', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.injectAxe()
  })
  it('Has Navigation', () => {
    cy.findByRole('navigation')
      .findByText(/about/i)
      .click()
      .url().should('include', '/about')
    cy.WCAG2a()
    cy.findByRole('navigation')
      .findByText(/lab/i)
      .click()
      .url().should('include', '/labs')
    cy.WCAG2a()
    cy.findByRole('navigation')
      .findByText(/posts/i)
      .click()
      .url().should('include', '/posts')
    cy.WCAG2a()
    cy.findByRole('navigation')
      .findByText(/say hello/i)
      .click()
      .url().should('include', 'contact')
    cy.WCAG2a()
    cy.findAllByRole('heading')
      .findByText(/alex edwards/i)
      .click()
    cy.assertHome()
  })

})
